---
- name: Using inline definition
  hosts: docker.iomate.local
  gather_facts: no
  tasks:
    - docker_service:
        state: present
        project_name: my_service
        definition:
          version: '2'
          services:
            drupal:
              image: drupal
              ports:
                - "8080:80"
              volumes:
                - drupal-modules:/var/www/html/modules
                - drupal-profiles:/var/www/html/profiles
                - drupal-sites:/var/www/html/sites
                - drupal-themes:/var/www/html/themes
            postgres:
              image: postgres
              environment:
                - POSTGRES_PASSWORD=mypasswd
          volumes:
            drupal-modules:
            drupal-profiles:
            drupal-sites:
            drupal-themes: